# Generated by Django 5.1.5 on 2025-01-30 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebooks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mybooks',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='book_images/'),
        ),
        migrations.AlterField(
            model_name='mybooks',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
