# Generated by Django 5.1.5 on 2025-01-30 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebooks', '0002_mybooks_image_alter_mybooks_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mybooks',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
